EzModel[] objects
EzModel[] obstacles
EzModel gripper
string[] finger_joint_names

float64 pose_factor

string gripper_frame
---
bool success
string[] info
int32[] error_codes

int32 EXCEPTION = -1
int32 SUCCESS = 0
int32 NO_FINGER_JOINTS = 1
int32 INVALID_POSE_FACTOR = 2
int32 NO_FRAME_ID = 3
int32 DUPLICATE_NAME = 4
int32 NO_FILENAME = 5
int32 NO_NAME = 6
int32 ADD_MODEL_ERROR = 7
int32 LOAD_MODEL_ERROR = 8

# -1 = An exception occured
# 0 = Success
# 1 = Invalid service input: No finger_joint_names provided
# 2 = Invalid service input: pose_factor is negative or zero
# 3 = Invalid service input: No frame_id in PoseStamped message
# 4 = Invalid service input: Duplicate object or obstacle name
# 5 = Invalid service input: No filename provided
# 6 = Invalid service input: No name provided
# 7 = Error while adding a model in the graspit database
# 8 = Error while loading a model from the graspit database